# Generated by Django 3.0.4 on 2020-03-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gratitudes', '0002_auto_20200311_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='gratitude',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
